### ISSUE TITLE
File extension length more than 3 characters (eg: .html) gets renamed in the final FATFS image

### ISSUE THREAD

**Issue by sriharsha-rbnd** [TobleMiner/mk_esp32fat#3]
TobleMiner,

Thanks for sharing the mkfatfs tool with wear levelling support. 

While testing the tool, I found issue with packing files into FATFS image which have file extension character length more than 3 (eg: .html or .conf). Files with more than 3 char length in thier file extension get renamed in the final image.

**Sharing the output of mkfatfs tool while preparing the FATFS image:**

> $ ./mkfatfs -t ../../build/default.bin fatfs.img
Adding files:
	Adding file 'image/dcfg.txt' => '/dcfg.txt'
	Adding file 'image/style.css' => '/style.css'
	Adding file 'image/ci.png' => '/ci.png'
	Adding file 'image/rt.png' => '/rt.png'
	Adding file 'image/index.html' => '/index.html'
Saving fatfs image to 'fatfs.img'
Saving 1503232 bytes to file
Image complete

**Serial output of ESP32 after mounting the FATFS:**

> Listing directory: /
FILE: /DCFG.TXT		SIZE: 312
FILE: /STYLE.CSS	        SIZE: 428
FILE: /CI.PNG		        SIZE: 4821
FILE: /RT.PNG		SIZE: 12144
FILE: /INDEX~1.HTM	SIZE: 1096
[E][vfs_api.cpp:64] open(): /index.html does not exist

Here the file **index.html** has been renamed to **index~1.htm**. If I open the file with **index~1.htm** name, I can read the file content.

I am using ESP-IDF v3.2.2 and mkfatfs tool was built on Ubuntu 16.04 64-bit machine but the binary is of 32-bit .

>  $ file mkfatfs 
mkfatfs: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 2.6.32, BuildID[sha1]=e094083ace9d5a79bcc5373c21566b59506a3dac, not stripped

I understood, FAT file system is case insensitive for all the file operations from this thread: https://www.esp32.com/viewtopic.php?t=5413 but I could not find any explanation for renaming of file if file extension is more than 3 chars.

It is not clear whether the is issue with mkfatfs tool or the ESP-IDF Arduino FFAT component which causes this renaming of the file during mounting. Please help me out in debugging this.

**Comment by TobleMiner** [comment]
Wow, that's interesting. The project I've built this tool for uses filenames with extensions longer than 3 characters. I've used it successfully with esp-idf, neither the exact version you are using nor Arduino though. I'll investigate this. Thanks for reporting.

**Comment by sriharsha-rbnd** [comment]
Sorry, my bad. I dint look around FAT file system component options of ESP-IDF.
Following options need to set via 'make menuconfig':

> CONFIG_FATFS_LFN_NONE=
CONFIG_FATFS_LFN_HEAP=y
CONFIG_FATFS_LFN_STACK=
CONFIG_FATFS_MAX_LFN=255
CONFIG_FATFS_API_ENCODING_ANSI_OEM=y
CONFIG_FATFS_API_ENCODING_UTF_16=
CONFIG_FATFS_API_ENCODING_UTF_8=

Basically, long file name support has to be enabled for FAT file system component of ESP-IDF. 
FATFS image built from the tool works fine on ESP32 after above IDF change. May be this can be added as a note in your README. 

I am closing this issue. Thanks once again for the wonderful tool and your swift response.

**Comment by TobleMiner** [comment]
Hey, no worrys. Glad you figured it out :)
